language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r yh-springboot-project *
  - mkdir -p deploy
  - mv yh-springboot-project.zip deploy/yh-springboot-project.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY

    secret_access_key: $AWS_SECRET_KEY

    bucket: yh-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl : private
    local_dir: deploy
    wait-until-deployed : true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY

    secret_access_key: $AWS_SECRET_KEY

    bucket: yh-springboot-build
    key: yh-springboot-project.zip
    bundle_type: zip
    application: yh-springboot-webservice
    deployment_group: yh-springboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - yhkim1031@gmail.com